Графика для всех страниц
htmlacademy-htmlcss/1875121-sedona-34 pull request #3
Opened 2022-05-28 16:55 UTC by Kertonianec

2022-05-29 13:39 UTC, Dima-Dim requested changes
images/counter.svg - а если нужно будет другую цифры в кружёчке, новую svg будем делать? :)

2022-05-29 14:01 UTC, Kertonianec commented
:) возникал такой вопрос. Наверно берётся сама иконка избранного, а остальное осуществляется через js?

2022-05-29 14:08 UTC, Dima-Dim commented
> :) возникал такой вопрос. Наверно берётся сама иконка избранного, а остальное осуществляется через js?

Что из себя, в таком случае, из себя представляет эта иконка?

2022-05-29 14:13 UTC, Kertonianec commented
Счётчик

2022-05-29 14:18 UTC, Kertonianec commented
Сама иконка(сердце) это избранное, а цифра это сколько заложено в избранное

2022-05-29 15:14 UTC, Kertonianec commented
Нужно просто добавить иконку без цифр, я правильно понял?

2022-05-29 16:09 UTC, Dima-Dim commented
> Нужно просто добавить иконку без цифр, я правильно понял?

Да.

2022-06-02 07:14 UTC, Dima-Dim approved these changes

2022-06-02 07:14 UTC, merged