Декоративные элементы всех страниц
htmlacademy-htmlcss/1875121-sedona-34 pull request #8
Opened 2022-07-05 21:35 UTC by Kertonianec

2022-07-06 12:02 UTC, Dima-Dim requested changes

2022-07-06 12:02 UTC, Dima-Dim commented on catalog.html
> +              <svg class="navigation-icon" aria-hidden="true" focusable="false" width="19" height="19" fill="none" xmlns="http://www.w3.org/2000/svg">
Для чего это svg в разметке? Такой же вопрос и по остальным декоративным элементам, которые появились в разметке.

2022-07-06 15:48 UTC, Kertonianec commented on catalog.html
> +              <svg class="navigation-icon" aria-hidden="true" focusable="false" width="19" height="19" fill="none" xmlns="http://www.w3.org/2000/svg">
Вечер добрый, есть затруднения с звездами.
Возможно так?!
.hotel-star {
  grid-row: 5 / 6;
  width: 90px;
  background-image: url("../images/star.svg"), url("../images/star.svg");
  background-repeat: repeat-x;
  background-position: 0 center, 24px center;
  background-size: 18px 17px;
}

2022-07-07 06:26 UTC, Dima-Dim requested changes

2022-07-07 06:26 UTC, Dima-Dim commented on catalog.html
> +                <span class="hotel-good-rating"></span>
Выглядит как https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

2022-07-07 06:26 UTC, Dima-Dim commented on index.html
> +                <p class="advantages-description advantages-city-description">Седона — не аттракцион для<br> туристов, там течёт своя<br> жизнь</p>
Почему не шириной переносы регулируются?

2022-07-07 06:26 UTC, Dima-Dim commented on styles/styles.css
> +.navigation-user .navigation-item:nth-child(1) .navigation-link {
https://up.htmlacademy.ru/htmlcss/34/criteries#CSS-03

2022-07-07 07:12 UTC, Kertonianec commented on index.html
> +                <p class="advantages-description advantages-city-description">Седона — не аттракцион для<br> туристов, там течёт своя<br> жизнь</p>
Так как некоторые тексты не попадают в шаблон, поэтому решил сделать так.

2022-07-07 07:13 UTC, Kertonianec commented on catalog.html
> +                <span class="hotel-good-rating"></span>
Звёзды через псевдо оформлять?

2022-07-07 07:20 UTC, Dima-Dim commented on catalog.html
> +                <span class="hotel-good-rating"></span>
Да, но мыслить нужно чуть шире. Это не только визуальная составляющая, но и смысловая. Смысловая должна быть в разметке, в удобном для восприятия виде. Визуальная, т.к. в данном случае она декоративная, по возможности, должна быть убрана из разметки.

2022-07-07 07:24 UTC, Kertonianec commented on catalog.html
> +                <span class="hotel-good-rating"></span>
Хорошо, уберу.

2022-07-07 11:43 UTC, Kertonianec commented on catalog.html
> +                <span class="hotel-good-rating"></span>
Есть вопрос, а как тогда вставлять определенное количество звёзд в разные карточки, без обертки?

2022-07-07 12:07 UTC, Kertonianec commented on catalog.html
> +                <span class="hotel-good-rating"></span>
Либо я не правильно понял и по итогу в данный момент сделано правильно.В разметке пустой спан с определенным классом, а в стилях согласно классу,задано определенное количество звёзд.

2022-07-08 05:07 UTC, Dima-Dim commented on catalog.html
> +                <span class="hotel-good-rating"></span>
> а как тогда вставлять определенное количество звёзд в разные карточки, без обертки?

А почему спан обязательно должен быть именно пустым? Если он пустой, то и смысла в нём нет, но на самом то деле смысл в нём есть. Дак опиши этот смысл. Извини, кажется, дал слишком "толстую" подсказку :)

2022-07-09 05:09 UTC, merged